/* Design: an understated Japanese financial notebook. Snapshot-first chronology,
   source-separated opinions, locally stored personal tracking. No trade execution. */
const {useState,useEffect}=React;
const srcName={ipo96ut:'96ut',ipokiso:'IPOkiso'};
const stateNames={all:'全部 IPO',open:'申购中',deadline:'截止日',purchase:'购买中',waiting:'待申购',listed:'已上市',closed:'待公布',saved:'我的关注'};
const findField=(d,pattern)=>Object.entries(d?.fields||{}).find(([k])=>pattern.test(k.replace(/\s/g,'')))?.[1]||'';
function dates(s){return [...(s||'').matchAll(/(?:(20\d{2})[年/])?(\d{1,2})[月/](\d{1,2})/g)].map(m=>`${m[1]||'2026'}-${m[2].padStart(2,'0')}-${m[3].padStart(2,'0')}`)}
function fmt(d){return d?`${Number(d.slice(5,7))}/${Number(d.slice(8,10))}`:'暂无数据'}
function period(ds){return ds.length>1?`${fmt(ds[0])} — ${fmt(ds[1])}`:fmt(ds[0])}
function num(s){return Number(String(s||'').replace(/,/g,'').match(/[\d.]+/)?.[0]||0)}
function prep(c){const a=c.ipo96ut||{},b=c.ipokiso||{},ad=c.ipo96ut_detail||{},bd=c.ipokiso_detail||{};
 const bb=dates(b.application_period||findField(ad,/ＢＢ期間|BB期間/));
 const buy=dates(findField(bd,/購入申込期間/)||findField(ad,/購入申込期間/));
 const listing=dates(b.listing_date||a.listing_date)[0];
 const lottery=dates(findField(bd,/当選発表日/))[0];
 return {...c,name:a.kabu_name||b.kabu_name,market:b.market||a.market,bb,buy,listing,lottery,
 rating96:a.rating||'-',ratingK:b.overall_rating||'-',range:b.provisional_range||a.provisional_range,
 expected:a.expected_price||b.expected_price,offer:b.offering_price||a.offering_price,
 website:bd.website||ad.website||'',business:ad.business||bd.business||''};}
function status(c,day){if(c.listing&&day>=c.listing)return 'listed';if(c.buy.length===2&&day>=c.buy[0]&&day<=c.buy[1])return 'purchase';if(c.bb.length===2){if(day===c.bb[1])return 'deadline';if(day>=c.bb[0]&&day<c.bb[1])return 'open';if(day<c.bb[0])return 'waiting'}return 'closed'}
function timelineStage(c,day){const s=status(c,day);return s==='listed'?3:s==='purchase'?2:s==='closed'?1:s==='waiting'?-1:0}
function Rating({value}){const grade=/[SABCD]/.exec(value||'')?.[0]||'—';return <span className={`rating ${grade==='—'?'none':grade}`} title={value}>{grade}</span>}
function Status({value}){return <span className={`badge ${value}`}>{stateNames[value]}</span>}
function External({href,children,...rest}){return href?<a href={href} target="_blank" rel="noopener noreferrer" {...rest}>{children}</a>:<span {...rest}>{children}</span>}
function SourceLink({c,source}){return <External href={c[source+'_detail']?.url} className="source-label">{srcName[source]} ↗</External>}
function readLocal(key,fallback){try{return JSON.parse(localStorage.getItem(key))||fallback}catch{return fallback}}
function App(){const [data,setData]=useState(null),[error,setError]=useState('');const [saved,setSaved]=useState(()=>readLocal('ipo-note-saved',[]));
 const [filter,setFilter]=useState(new URLSearchParams(location.search).get('view')==='saved'?'saved':'all'),[q,setQ]=useState(''),[market,setMarket]=useState('all'),[sort,setSort]=useState('deadline');
 const [toast,setToast]=useState('');
 useEffect(()=>{fetch('data.json').then(r=>{if(!r.ok)throw Error('读取数据失败');return r.json()}).then(d=>setData({...d,companies:d.companies.map(prep)})).catch(e=>setError(e.message))},[]);
 useEffect(()=>{localStorage.setItem('ipo-note-saved',JSON.stringify(saved))},[saved]);
 useEffect(()=>{if(toast){const t=setTimeout(()=>setToast(''),2400);return()=>clearTimeout(t)}},[toast]);
 const toggle=c=>{setSaved(s=>s.includes(c.code)?s.filter(x=>x!==c.code):[...s,c.code]);setToast(saved.includes(c.code)?'已取消关注':'已加入关注 · 保存在此浏览器')};
 if(error)return <div className="empty">{error}。请通过本地 HTTP 服务打开页面。</div>;
 if(!data)return <div className="loading">正在载入 IPO 数据…</div>;
 const detail=location.pathname.endsWith('detail.html');const code=new URLSearchParams(location.search).get('code')||'627A';const c=data.companies.find(x=>x.code===code);
 return <><header className="topbar"><a href="index.html?v=3" className="brand"><span className="brand-mark">i</span><span>IPO NOTE<small>日本新股观察</small></span></a><nav className="topnav" aria-label="主导航"><a className={!detail&&filter!=='saved'?'selected':''} href="index.html?v=3">IPO 一览</a><a className={!detail&&filter==='saved'?'selected':''} href="index.html?v=3&view=saved">我的关注 <span className="subtle">&nbsp;{saved.length}</span></a></nav><div className="top-right"><span><i className="dot"></i>双来源数据</span><span className="avatar">JP</span></div></header>
 <main className="shell">{detail?(c?<Detail c={c} day={data.snapshot_date} saved={saved.includes(c.code)} toggle={()=>toggle(c)} notify={setToast}/>:<div className="empty">未找到股票代码 {code}。<a href="index.html?v=3">返回一览</a></div>):<Listing data={data} saved={saved} toggle={toggle} filter={filter} setFilter={setFilter} q={q} setQ={setQ} market={market} setMarket={setMarket} sort={sort} setSort={setSort}/>}
 <footer className="footer"><span>IPO NOTE · 日本新股观察　 /　数据来源：96ut、IPOkiso</span><span>列表快照 {data.snapshot_date} · 日本时间 JST · 本地交互原型</span></footer></main>{toast&&<div className="toast" role="status">{toast}</div>}</>;
}
function Listing({data,saved,toggle,filter,setFilter,q,setQ,market,setMarket,sort,setSort}){const day=data.snapshot_date,all=data.companies;
 const count=t=>all.filter(c=>t==='open'?['open','deadline'].includes(status(c,day)):status(c,day)===t).length;
 let rows=all.filter(c=>(filter==='all'||(filter==='saved'?saved.includes(c.code):filter==='open'?['open','deadline'].includes(status(c,day)):status(c,day)===filter))&&(!q||`${c.name} ${c.code}`.toLowerCase().includes(q.toLowerCase()))&&(market==='all'||c.market.includes(market)));
 rows.sort((a,b)=>{if(sort==='listing')return (a.listing||'').localeCompare(b.listing||'');if(sort==='price')return num(a.expected)-num(b.expected);const priority=c=>['deadline','open','purchase','waiting','closed','listed'].indexOf(status(c,day));return priority(a)-priority(b)||(a.bb[1]||'').localeCompare(b.bb[1]||'')});
 const events=all.filter(c=>c.bb[1]>=day).sort((a,b)=>a.bb[1].localeCompare(b.bb[1])).slice(0,4);
 return <div data-screen-label="IPO 一览"><div className="heading"><div><div className="eyebrow">IPO WATCH / SEPTEMBER 2026</div><h1>{filter==='saved'?'我的关注':'每一次申购，心中有数。'}</h1><p>追踪日本新股日程，对照两站观点，把握下一步。</p></div><span className="snapshot">数据快照　2026.09.07 <span className="subtle"> / JST</span></span></div>
 <div className="stat-grid"><button className="stat green" onClick={()=>setFilter('open')}><span className="label">正在申购 <span>↗</span></span><strong>{count('open').toString().padStart(2,'0')}</strong><small>含截止日项目</small></button><button className="stat urgent" onClick={()=>setFilter('deadline')}><span className="label">快照日截止 <span>↗</span></span><strong>{count('deadline').toString().padStart(2,'0')}</strong><small>请核对各券商具体截止时刻</small></button><button className="stat" onClick={()=>setFilter('purchase')}><span className="label">进入购买期 <span>↗</span></span><strong>{count('purchase').toString().padStart(2,'0')}</strong><small>中签后记得完成购买</small></button><button className="stat" onClick={()=>setFilter('waiting')}><span className="label">即将开放申购 <span>↗</span></span><strong>{count('waiting').toString().padStart(2,'0')}</strong><small>提前了解公司与发行信息</small></button></div>
 <div className="main-grid"><section className="panel"><div className="panel-head"><h2>IPO 日程一览</h2><small>9 — 10 月 · {all.length} 家公司</small></div><div className="tabs">{['all','open','purchase','waiting','saved'].map(t=><button key={t} className={filter===t?'on':''} onClick={()=>setFilter(t)}>{stateNames[t]}<small>{t==='all'?all.length:t==='saved'?saved.length:count(t)}</small></button>)}{filter==='deadline'&&<button className="on">截止日 <small>{count('deadline')}</small></button>}</div>
 <div className="toolbar"><label className="search"><span aria-hidden="true">⌕</span><input aria-label="搜索公司或代码" placeholder="搜索公司名称 / 股票代码" value={q} onChange={e=>setQ(e.target.value)}/></label><select aria-label="市场筛选" value={market} onChange={e=>setMarket(e.target.value)}><option value="all">全部市场</option><option value="スタンダード">东证 Standard</option><option value="グロース">东证 Growth</option><option value="ネクスト">名证 Next</option></select><select aria-label="排序" value={sort} onChange={e=>setSort(e.target.value)}><option value="deadline">按申购截止排序</option><option value="listing">按上市日排序</option><option value="price">按想定价排序</option></select></div>
 <div className="table-wrap"><table className="list-table"><thead><tr><th>公司 / 代码</th><th>状态</th><th>申购期间</th><th>购买期间</th><th>上市日</th><th className="ratings-cell">96ut / IPOkiso</th><th>关注</th></tr></thead><tbody>{rows.map(c=><tr key={c.code}><td className="company-cell"><a className="company-name" href={`detail.html?v=3&code=${c.code}`} lang="ja">{c.name}</a><span className="code">{c.code} · {c.market.replace('東証 ','').replace('スタンダード','Standard').replace('グロース','Growth').replace('名証 ネクスト','名证 Next')}</span></td><td><Status value={status(c,day)}/></td><td className="date">{period(c.bb)}<small className={status(c,day)==='deadline'?'soon':''}>{status(c,day)==='deadline'?'快照日截止':status(c,day)==='waiting'?'尚未开放':'来源 IPOkiso'}</small></td><td className="date">{period(c.buy)}<small>来源 IPOkiso / 96ut</small></td><td className="date">{fmt(c.listing)}</td><td><div className="rating-pair"><Rating value={c.rating96}/><Rating value={c.ratingK}/></div></td><td><button className={`star ${saved.includes(c.code)?'saved':''}`} aria-label={`${saved.includes(c.code)?'取消关注':'关注'} ${c.name}`} aria-pressed={saved.includes(c.code)} onClick={()=>toggle(c)}>{saved.includes(c.code)?'★':'☆'}</button></td></tr>)}</tbody></table>{!rows.length&&<div className="empty">没有匹配的 IPO。试试其他筛选条件。<br/><button onClick={()=>{setQ('');setMarket('all');setFilter('all')}}>重置筛选</button></div>}</div><div className="table-foot"><span>显示 {rows.length} / {all.length} 家公司</span><span>点击公司名称查看详情 →</span></div><div className="list-header-note">评级沿用列表快照；购买日程来自详情补采。状态按快照日的日期推算，不代表当前可申购。</div></section>
 <aside className="aside list-aside"><section className="panel"><div className="aside-kicker">UP NEXT</div><h3>最近申购截止</h3>{events.map(c=><div className="event" key={c.code}><div className={`event-day ${c.bb[1]===day?'urgent':''}`}>{Number(c.bb[1].slice(8))}<small>9 月</small></div><div className="event-info"><a href={`detail.html?v=3&code=${c.code}`}><strong>{c.name}</strong></a><p>{c.code} · 申购截止</p><a href={`detail.html?v=3&code=${c.code}`}>查看日程 ↗</a></div></div>)}</section><section className="panel note"><div className="aside-kicker">TWO PERSPECTIVES</div><h3>两份评级，独立参考。</h3><p>两站对同一只股票可能有不同判断。详情页将评级、初值预测与评价原文并列展示，保留各自的来源。</p><a href="detail.html?v=3&code=627A" className="source-label">看看 akippa 的两站观点 →</a></section><section className="panel"><h3>数据来源</h3><div className="source-legend"><span>96ut <small>2026.09.07</small></span><span>IPOkiso <small>2026.09.07</small></span></div><p className="mini-note">列表快照与详情补采时间分别保留。未获取的值以“暂无数据”呈现。</p></section></aside></div></div>
}
function Review({c,source}){const [expanded,setExpanded]=useState(false);const d=c[source+'_detail']||{};let content=(d.comments||[]).map(x=>x.text).join('\n\n');content=content.replace(/@ipokiso_com[\s\S]*$/,'').trim();if(source==='ipo96ut'&&content.includes('・新規承認時'))content=content.slice(content.indexOf('・新規承認時'));
 const forecast=findField(d,source==='ipo96ut'?/初値予想\(BB開始時\)/:/初値予想/);return <article className={`review ${expanded?'expanded':''}`}><div className="review-top"><div><h3>{srcName[source]}</h3><small>网站独立评级 · 列表快照</small></div><Rating value={source==='ipo96ut'?c.rating96:c.ratingK}/></div><div className="forecast"><span className="subtle">{source==='ipo96ut'?'初值预测 · BB 开始时':'初值预测 · 网站独自预测'}</span><strong>{forecast?forecast.split(/[（(]/)[0]:'暂无数据'}</strong>{forecast&&/[（(]/.test(forecast)&&<small>{forecast.slice(forecast.search(/[（(]/))}</small>}</div><p className="review-body" lang="ja">{content||'暂无评价原文，请查看来源页面。'}</p><div className="review-actions"><button onClick={()=>setExpanded(!expanded)}>{expanded?'收起评价 −':'展开评价全文 +'}</button><SourceLink c={c} source={source}/></div><small>详情补采：{d.retrieved_at?new Date(d.retrieved_at).toLocaleDateString('zh-CN',{timeZone:'Asia/Tokyo'}):'暂无数据'} · 日文原文</small></article>}
function downloadCalendar(c){const events=[['申购截止',c.bb[1]],['购买开始',c.buy[0]],['购买截止',c.buy[1]],['上市日',c.listing]].filter(x=>x[1]);
 const content=['BEGIN:VCALENDAR','VERSION:2.0','PRODID:-//IPO NOTE//CN','CALSCALE:GREGORIAN',...events.flatMap(([name,date],i)=>['BEGIN:VEVENT',`UID:${c.code}-${i}@ipo-note.local`,`DTSTAMP:${new Date().toISOString().replace(/[-:]/g,'').replace(/\.\d{3}/,'')}`,`DTSTART;VALUE=DATE:${date.replace(/-/g,'')}`,`SUMMARY:${c.name} ${c.code} ${name}`,'DESCRIPTION:日期来自 IPO 快照；请在券商核对具体时间。','END:VEVENT']),'END:VCALENDAR'].join('\r\n');const u=URL.createObjectURL(new Blob([content],{type:'text/calendar;charset=utf-8'}));const a=document.createElement('a');a.href=u;a.download=`${c.code}-ipo.ics`;a.click();setTimeout(()=>URL.revokeObjectURL(u),1000)}
function Detail({c,day,saved,toggle,notify}){const [checked,setChecked]=useState(()=>readLocal('ipo-note-check-'+c.code,{}));const ad=c.ipo96ut_detail||{},bd=c.ipokiso_detail||{};const af=ad.fields||{},bf=bd.fields||{};const setCheck=k=>setChecked(prev=>{const next={...prev,[k]:!prev[k]};localStorage.setItem('ipo-note-check-'+c.code,JSON.stringify(next));return next});
 const brokers=c.ipokiso?.target_securities||[];const docs=[...(ad.documents||[]),...(bd.documents||[])];const business=c.business.replace(/^.*?事業内容\s*[:：]?/,'').trim();
 return <div data-screen-label="股票详情"><div className="breadcrumb"><a href="index.html?v=3">IPO 一览</a><span>/</span><span>{c.name} · {c.code}</span></div><div className="detail-top"><div className="detail-heading"><div className="monogram">{c.name.match(/[a-zA-Z]/)?.[0]||'株'}</div><div><h1 lang="ja">{c.name}</h1><div className="detail-title-meta"><span>{c.code} · {c.market}</span><Status value={status(c,day)}/></div></div></div><div className="action-group"><button onClick={toggle}>{saved?'★ 已关注':'☆ 加入关注'}</button><button className="primary" onClick={()=>{downloadCalendar(c);notify('IPO 日程已导出为日历文件')}}>＋ 导出 IPO 日程</button></div></div>
 <div className="metric-strip"><div className="metric"><span>想定价格</span><strong>¥ {num(c.expected).toLocaleString()}</strong><small>来源 96ut / IPOkiso</small></div><div className="metric"><span>仮条件 · 发行价格区间</span><strong>{c.range&&c.range!=='-'?`¥ ${c.range.replace(/円/g,'').replace(/～/g,'—')}`:'尚未公布'}</strong><small>来源 IPOkiso · 每股日元</small></div><div className="metric"><span>公募价格</span><strong>{c.offer&&c.offer!=='-'?`¥ ${num(c.offer).toLocaleString()}`:'尚未公布'}</strong><small>来源 IPOkiso</small></div><div className="metric"><span>上市日期</span><strong>{fmt(c.listing)} <span style={{display:'inline',fontSize:13}}>2026</span></strong><small>{c.market}</small></div></div>
 <div className="detail-grid"><div className="detail-main"><section className="panel"><div className="panel-head"><h2>申购到上市，一步不漏</h2><small>日本时间 · JST</small></div><div className="timeline">{[['申购期间',period(c.bb),'截止后不可补报'],['中签公布',fmt(c.lottery),'以券商账户结果为准'],['购买期间',period(c.buy),'中签后完成购买'],['上市交易',fmt(c.listing),'关注首日交易']].map(([title,value,note],i)=><div key={title} className={`step ${i===timelineStage(c,day)?'current':''}`}><small>0{i+1} / {title}</small><strong>{value}</strong><span>{note}</span></div>)}</div><p className="disclaimer">状态基准：{day} 列表快照。日程来源 IPOkiso / 96ut；各券商具体截止时刻可能不同。</p></section>
 <nav className="section-nav" aria-label="详情章节"><a href="#company">公司概况</a><a href="#opinions">两站评价</a><a href="#financials">财务数据</a><a href="#brokers">申购券商</a></nav>
 <section id="company" className="panel"><div className="panel-head"><h2>这是一家怎样的公司？</h2><External href={c.website} className="source-label">公司官网 ↗</External></div><div className="section-content"><p className="business-text" lang="ja">{business||'暂无公司业务介绍。'}</p><div className="facts">{[['公司成立',af['設立']||bf['会社設立']],['员工人数',af['従業員数']],['主承销商',af['主幹事証券']||bf['主幹事証券']],['审计机构',af['監査法人']],['公司所在地',af['所在地']],['募集资金用途',af['IPOの資金用途']]].map(([k,v])=><div className="fact" key={k}><span>{k}</span><strong lang="ja">{v||'暂无数据'}</strong></div>)}</div><p className="mini-note">资料来源：96ut；成立时间及主承销商缺失时采用 IPOkiso。</p></div></section>
 <section id="opinions" className="panel"><div className="panel-head"><h2>两站观点，放在一起看</h2><span className="subtle" style={{fontSize:11}}>独立评级 · 保留原文</span></div><div className="analysis-grid"><Review c={c} source="ipo96ut"/><Review c={c} source="ipokiso"/></div><p className="disclaimer">评级沿用 2026.09.07 列表快照，预测与评价取自详情补采。两站评级口径不同，不做平均或统一打分。</p></section>
 <section id="financials" className="panel"><div className="panel-head"><h2>公司财务</h2><SourceLink c={c} source="ipokiso"/></div>{bd.financials?.length?<div className="table-wrap financial"><table><thead><tr>{bd.financials[0][0].map((v,i)=><th key={i}>{v||'财务指标'}</th>)}</tr></thead><tbody>{bd.financials[0].slice(1).map((r,i)=><tr key={i}>{r.map((v,j)=><td key={j} className={v.includes('△')?'urgent':''}>{v}</td>)}</tr>)}</tbody></table></div>:<div className="section-content subtle">暂无已获取财务数据，请参考原始披露文件。</div>}<p className="disclaimer" style={{paddingTop:16}}>保留原表单位及负数标记；金额、每股指标的单位请以行标题为准。</p></section></div>
 <aside className="aside detail-aside"><section className="panel check-panel"><div className="aside-kicker">MY IPO NOTE</div><h3>我的申购备忘</h3><p className="subtle">仅保存在此浏览器，不代表券商状态。</p>{[['applied','已向券商提交申购'],['result','已确认中签结果'],['purchased','已完成中签购买']].map(([k,label])=><label className="checkline" key={k}><input type="checkbox" checked={!!checked[k]} onChange={()=>setCheck(k)}/>{label}</label>)}<button className="primary" onClick={()=>document.getElementById('brokers').scrollIntoView({behavior:'smooth'})}>查看申购券商 ↓</button><p className="mini-note">实际申购与购买请在券商账户中完成。</p></section><section className="panel" id="brokers"><div className="aside-kicker">WHERE TO APPLY</div><h3>可申购券商</h3>{brokers.map((b,i)=><div className="broker" key={i}><External href={b.url?new URL(b.url,'https://www.ipokiso.com').href:''}>{b.name}{b.url?' ↗':''}</External><small>{b.role==='主'?'主承销':b.role==='副'?'副承销':'申购渠道'}</small></div>)}<p className="mini-note">来源 IPOkiso。链接前往券商介绍页，可查找开户与申购入口。</p></section><section className="panel"><div className="aside-kicker">DOCUMENTS</div><h3>公司披露资料</h3>{docs.length?docs.map((d,i)=><External key={i} href={d.url} className="document-link"><span>{d.title}</span><span>↗</span></External>):<p className="subtle">暂无已获取资料。</p>}</section></aside></div></div>
}
ReactDOM.createRoot(document.getElementById('root')).render(<App/>);
